[package]
edition = "2021"
name = "udpx"
version = "0.1.0"

[dev-dependencies]
clippy = "0.0.302"

[dependencies]
clap = {version = "3.1.6", features = ["derive", "wrap_help"]}
env_logger = "0.9.0"
log = "0.4.16"
mime = "0.3.16"
rand = "0.8.5"
threadpool = "1.8.1"
ureq = "2.4.0"
