[package]
default-run = "httpfs"
edition = "2021"
name = "httpfs"
version = "0.1.0"

[dependencies]
clap = {version = "3.1.6", features = ["derive", "wrap_help"]}
env_logger = "0.9.0"
log = "0.4.14"
mime = "0.3.16"
num_cpus = "1.13.1"
threadpool = "1.8.1"
