name: Build

on:
  pull_request:
  push:
    branches:
      - "*"
      # - main
      # - parser
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        required: false
        description: "Test scenario tags"

jobs:
  test-go:
    name: Run Go tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version:
          - "1.18" # Generics
          # - "1.17"
          # - "1.16"
          # - "1.15"
          # - "1.14"
    steps:
      - uses: actions/checkout@v2
      - name: Use go${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: make test
      - run: make
      - run: |
          make static
          file httpc | grep 'statically linked'

  test-rust:
    name: Run Rust tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    strategy:
      fail-fast: true
      matrix:
        rust-version:
          - stable
    steps:
      - uses: actions/checkout@v2
      - name: Use rust ${{ matrix.rust-version }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
      - uses: Swatinem/rust-cache@v1
      - run: make test
      - run: make
      - run: |
          make static
          file target/x86_64-unknown-linux-gnu/release/httpfs | grep 'statically linked'
